line-length = 120

target-version = "py311"

[lint]
select = ["ARG", "ASYNC", "B", "C4", "E", "F", "FIX", "FURB", "I", "PERF", "PIE", "PL", "RET", "RUF", "SIM", "SLF", "UP", "W"]
ignore = ["ASYNC109", "PLR2004", "RET502", "RET503", "SIM102", "SIM103"]

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.pylint]
max-args = 10
max-statements = 100
max-returns = 24
max-branches = 24

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
